# 통합 데이터 전처리

In [3]:
import pandas as pd
data=pd.read_csv("C:/bank.csv")
Y=data[['TARGET']]
X=data.drop(['Unnamed: 0','TARGET'],axis=1)
X.iloc[:,[42,43,44,63,64,65,66,67]] = X.iloc[:,[42,43,44,63,64,65,66,67]].astype('category')
X.iloc[:,[42,43,44,63,64,65,66,67]]=X.iloc[:,[42,43,44,63,64,65,66,67]].replace([1,2],[0,1])
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.3,random_state=1004)
from imblearn.over_sampling import SMOTENC
smote_nc = SMOTENC(categorical_features=[42,43,44,63,64,65,66,67], random_state=0)
X_smotenc, Y_smotenc = smote_nc.fit_resample(X_train, Y_train)

# Logistic Regression

In [6]:
#smotenc
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(X_smotenc,Y_smotenc)
Y_pred_log=log.predict(X_test)
#성능평가
from sklearn import metrics
log_accuracy=metrics.accuracy_score(Y_test,Y_pred_log)
log_score=metrics.precision_recall_fscore_support(Y_test,Y_pred_log)
print(log_accuracy)
print(log_score)

C:\Users\noble\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


0.8501157246033295
(array([0.99845023, 0.03722443]), array([0.8503707 , 0.81422925]), array([0.91848032, 0.07119406]), array([35608,   253], dtype=int64))


C:\Users\noble\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Decision Tree

In [7]:
#smotenc
from sklearn.tree import DecisionTreeClassifier
t1=DecisionTreeClassifier(max_depth=4, min_samples_split=50, min_samples_leaf=25)
t1.fit(X_smotenc,Y_smotenc)
Y_pred_dt=t1.predict(X_test)
#성능평가
tree_accuracy=metrics.accuracy_score(Y_test,Y_pred_dt)
tree_score=metrics.precision_recall_fscore_support(Y_test,Y_pred_dt)
print(tree_accuracy)
print(tree_score)

0.741892306405287
(array([0.99875085, 0.02329768]), array([0.74098517, 0.86956522]), array([0.85077226, 0.04537954]), array([35608,   253], dtype=int64))


# Naive Bayes

In [8]:
#smotenc
from sklearn.naive_bayes import CategoricalNB
catNB1=CategoricalNB()
catNB1.fit(X_smotenc,Y_smotenc)
Y_pred_nb=catNB1.predict(X_test)
#성능평가
naive_accuracy=metrics.accuracy_score(Y_test,Y_pred_nb)
naive_score=metrics.precision_recall_fscore_support(Y_test,Y_pred_nb)
print(naive_accuracy)
print(naive_score)

C:\Users\noble\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


0.7564206240762946
(array([0.99637962, 0.01762966]), array([0.75744215, 0.61264822]), array([0.86063468, 0.03427308]), array([35608,   253], dtype=int64))


# Random Forest

In [9]:
#smotenc
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=20, max_depth=5,random_state=0)
clf.fit(X_smotenc,Y_smotenc)
Y_pred_rf=clf.predict(X_test)
#성능평가
forest_accuracy=metrics.accuracy_score(Y_test,Y_pred_rf)
forest_score=metrics.precision_recall_fscore_support(Y_test,Y_pred_rf)
print(forest_accuracy)
print(forest_score)

C:\Users\noble\AppData\Local\Temp/ipykernel_18128/2966508572.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_smotenc,Y_smotenc)


0.8759655335880204
(array([0.99868766, 0.04589738]), array([0.87623568, 0.83794466]), array([0.93346298, 0.08702791]), array([35608,   253], dtype=int64))


# Multi Layer Perceptron

In [13]:
#smotenc
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10,), activation='logistic', solver='sgd', alpha=0.01, batch_size=32,learning_rate_init=0.1, max_iter=500)  
mlp.fit(X_smotenc, Y_smotenc)
Y_pred_mlp = mlp.predict(X_test)
#성능 평가
mlp_accuracy=metrics.accuracy_score(Y_test,Y_pred_mlp)
mlp_score=metrics.precision_recall_fscore_support(Y_test,Y_pred_mlp)
print(mlp_accuracy)
print(mlp_score)

C:\Users\noble\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


0.6991439167898273
(array([0.99963764, 0.02213353]), array([0.69725904, 0.96442688]), array([0.82150716, 0.04327392]), array([35608,   253], dtype=int64))


# Factorization Machine

In [12]:
import xlearn as xl
import numpy as np
# DMatrix transition, if use field ,use must pass field map(an array) of features
xdm_train = xl.DMatrix(X_smotenc, Y_smotenc)
xdm_test = xl.DMatrix(X_test, Y_test)
# Training task
fm_model = xl.create_fm()  # Use factorization machine
# we use the same API for train from file
# that is, you can also pass xl.DMatrix for this API now
fm_model.setTrain(xdm_train)    # Training data
fm_model.setValidate(xdm_test)  # Validation data
# param:
#  0. regression task
#  1. learning rate: 0.2
#  2. regular lambda: 0.002
#  3. evaluation metric: mae
param = {'task':'binary', 'lr':0.03,
         'lambda':0.0001, 'metric':'acc'}
# Start to train
# The trained model will be stored in model.out
fm_model.fit(param, './modeldm.out')
# Prediction task
# we use the same API for test from file
# that is, you can also pass xl.DMatrix for this API now
fm_model.setTest(xdm_test)  # Test data
fm_model.setSign() # Convert output to 0,1
# Start to predict
# The output result will be stored in output.txt
# if no result out path setted, we return res as numpy.ndarray
Y_pred_fm = fm_model.predict("./modeldm.out")
#성능 평가
from sklearn import metrics
fm_accuracy=metrics.accuracy_score(Y_test,Y_pred_fm)
fm_score=metrics.precision_recall_fscore_support(Y_test,Y_pred_fm)
print(fm_accuracy)
print(fm_score)

0.8276958255486462
(array([0.99807061, 0.03102248]), array([0.82807234, 0.77470356]), array([0.90515878, 0.05965606]), array([35608,   253], dtype=int64))
